// packages/theme-inertia-bookings-react/resources/js/Pages/Capell/Page.jsx
import ContentWidget from '../../Components/Capell/Widgets/Content.jsx'
import ImageWidget from '../../Components/Capell/Widgets/Image.jsx'
import TitleWidget from '../../Components/Capell/Widgets/Title.jsx'
import { sanitizePublicHtml } from '../../Support/publicHtml.js'

const widgets = {
    'Capell/Widgets/Content': ContentWidget,
    'Capell/Widgets/Image': ImageWidget,
    'Capell/Widgets/Title': TitleWidget,
}

export default function Page({ page }) {
    return (
        <main className="capell-inertia-bookings-page">
            <section className="capell-inertia-bookings-hero">
                {page.meta?.eyebrow ? <p>{page.meta.eyebrow}</p> : null}
                <h1>{page.title}</h1>
                {typeof page.content === 'string' ? (
                    <div
                        dangerouslySetInnerHTML={{
                            __html: sanitizePublicHtml(page.content),
                        }}
                    />
                ) : null}
                <a href="/bookings">Request appointment</a>
            </section>

            {(page.layout?.containers ?? []).map((container) => (
                <section
                    className="capell-inertia-bookings-container"
                    key={container.key}
                >
                    {container.widgets.map((widget) => {
                        const WidgetComponent =
                            widgets[widget.component] ?? ContentWidget

                        return (
                            <WidgetComponent
                                key={`${widget.key}:${widget.occurrence}`}
                                widget={widget}
                            />
                        )
                    })}
                </section>
            ))}
        </main>
    )
}

// packages/theme-inertia-bookings-vue/resources/js/Pages/Capell/Page.vue
<script setup>
import ContentWidget from '../../Components/Capell/Widgets/Content.vue'
import ImageWidget from '../../Components/Capell/Widgets/Image.vue'
import TitleWidget from '../../Components/Capell/Widgets/Title.vue'
import { sanitizePublicHtml } from '../../Support/publicHtml.js'

defineProps({
    page: {
        type: Object,
        required: true,
    },
})

const widgets = {
    'Capell/Widgets/Content': ContentWidget,
    'Capell/Widgets/Image': ImageWidget,
    'Capell/Widgets/Title': TitleWidget,
}
</script>

<template>
    <main class="capell-inertia-bookings-page">
        <section class="capell-inertia-bookings-hero">
            <p v-if="page.meta?.eyebrow">
                {{ page.meta.eyebrow }}
            </p>
            <h1>{{ page.title }}</h1>
            <div
                v-if="typeof page.content === 'string'"
                v-html="sanitizePublicHtml(page.content)"
            />
            <a href="/bookings">Request appointment</a>
        </section>

        <section
            v-for="container in page.layout?.containers ?? []"
            :key="container.key"
            class="capell-inertia-bookings-container"
            :data-container="container.key"
        >
            <component
                :is="widgets[widget.component] ?? ContentWidget"
                v-for="widget in container.widgets"
                :key="`${widget.key}:${widget.occurrence}`"
                :widget="widget"
            />
        </section>
    </main>
</template>
