// packages/theme-inertia-bookings-vue/resources/js/Pages/Capell/Bookings/Request.vue
<script setup>
import { Deferred, router, useForm } from '@inertiajs/vue3'

const props = defineProps({
    options: {
        type: Object,
        default: () => ({ services: [], staff: [], locations: [] }),
    },
    slots: {
        type: Array,
        default: () => [],
    },
    postUrl: {
        type: String,
        default: '/bookings',
    },
    timezone: {
        type: String,
        default: 'UTC',
    },
})

const form = useForm({
    service_id: '',
    staff_member_id: '',
    location_id: '',
    requested_starts_at: '',
    timezone: props.timezone,
    customer_name: '',
    customer_email: '',
    customer_phone: '',
    notes: '',
})

function reloadSlots() {
    router.reload({
        only: ['slots'],
        data: {
            service_id: form.service_id,
            staff_member_id: form.staff_member_id,
            location_id: form.location_id,
            timezone: form.timezone,
        },
    })
}
</script>

<template>
    <main class="capell-inertia-booking-request">
        <form @submit.prevent="form.post(postUrl)">
            <label>
                Service
                <select
                    v-model="form.service_id"
                    @change="reloadSlots"
                >
                    <option value="">Choose a service</option>
                    <option
                        v-for="service in options.services"
                        :key="service.id"
                        :value="service.id"
                    >
                        {{ service.name }}
                    </option>
                </select>
            </label>

            <label>
                Staff
                <select
                    v-model="form.staff_member_id"
                    @change="reloadSlots"
                >
                    <option value="">Any staff member</option>
                    <option
                        v-for="staffMember in options.staff"
                        :key="staffMember.id"
                        :value="staffMember.id"
                    >
                        {{ staffMember.display_name }}
                    </option>
                </select>
            </label>

            <label>
                Location
                <select
                    v-model="form.location_id"
                    @change="reloadSlots"
                >
                    <option value="">Choose a location</option>
                    <option
                        v-for="location in options.locations"
                        :key="location.id"
                        :value="location.id"
                    >
                        {{ location.name }}
                    </option>
                </select>
            </label>

            <label>
                Time
                <Deferred data="slots">
                    <template #fallback>
                        <select disabled>
                            <option>Choose service details first</option>
                        </select>
                    </template>

                    <select v-model="form.requested_starts_at">
                        <option value="">Choose a time</option>
                        <option
                            v-for="slot in slots"
                            :key="slot.starts_at"
                            :value="slot.starts_at"
                        >
                            {{ slot.label }}
                        </option>
                    </select>
                </Deferred>
            </label>

            <label>
                Name
                <input
                    v-model="form.customer_name"
                    autocomplete="name"
                    type="text"
                />
            </label>

            <label>
                Email
                <input
                    v-model="form.customer_email"
                    autocomplete="email"
                    type="email"
                />
            </label>

            <label>
                Phone
                <input
                    v-model="form.customer_phone"
                    autocomplete="tel"
                    type="tel"
                />
            </label>

            <label>
                Notes
                <textarea v-model="form.notes" />
            </label>

            <button
                :disabled="form.processing"
                type="submit"
            >
                Request appointment
            </button>
        </form>
    </main>
</template>

// packages/theme-inertia-bookings-react/resources/js/Pages/Capell/Bookings/Request.jsx
import { Deferred, router, useForm } from '@inertiajs/react'

export default function Request({
    options = { services: [], staff: [], locations: [] },
    slots = [],
    postUrl = '/bookings',
    timezone = 'UTC',
}) {
    const { data, setData, post, processing } = useForm({
        service_id: '',
        staff_member_id: '',
        location_id: '',
        requested_starts_at: '',
        timezone,
        customer_name: '',
        customer_email: '',
        customer_phone: '',
        notes: '',
    })

    function reloadSlots(nextData = data) {
        router.reload({
            only: ['slots'],
            data: {
                service_id: nextData.service_id,
                staff_member_id: nextData.staff_member_id,
                location_id: nextData.location_id,
                timezone: nextData.timezone,
            },
        })
    }

    function updateField(field, value, reload = false) {
        const nextData = { ...data, [field]: value }

        setData(field, value)

        if (reload) {
            reloadSlots(nextData)
        }
    }

    return (
        <main className="capell-inertia-booking-request">
            <form
                onSubmit={(event) => {
                    event.preventDefault()
                    post(postUrl)
                }}
            >
                <label>
                    Service
                    <select
                        value={data.service_id}
                        onChange={(event) =>
                            updateField('service_id', event.target.value, true)
                        }
                    >
                        <option value="">Choose a service</option>
                        {options.services.map((service) => (
                            <option
                                key={service.id}
                                value={service.id}
                            >
                                {service.name}
                            </option>
                        ))}
                    </select>
                </label>

                <label>
                    Staff
                    <select
                        value={data.staff_member_id}
                        onChange={(event) =>
                            updateField(
                                'staff_member_id',
                                event.target.value,
                                true,
                            )
                        }
                    >
                        <option value="">Any staff member</option>
                        {options.staff.map((staffMember) => (
                            <option
                                key={staffMember.id}
                                value={staffMember.id}
                            >
                                {staffMember.display_name}
                            </option>
                        ))}
                    </select>
                </label>

                <label>
                    Location
                    <select
                        value={data.location_id}
                        onChange={(event) =>
                            updateField('location_id', event.target.value, true)
                        }
                    >
                        <option value="">Choose a location</option>
                        {options.locations.map((location) => (
                            <option
                                key={location.id}
                                value={location.id}
                            >
                                {location.name}
                            </option>
                        ))}
                    </select>
                </label>

                <label>
                    Time
                    <Deferred
                        data="slots"
                        fallback={
                            <select disabled>
                                <option>Loading available times</option>
                            </select>
                        }
                    >
                        <select
                            value={data.requested_starts_at}
                            onChange={(event) =>
                                updateField(
                                    'requested_starts_at',
                                    event.target.value,
                                )
                            }
                        >
                            <option value="">Choose a time</option>
                            {slots.map((slot) => (
                                <option
                                    key={slot.starts_at}
                                    value={slot.starts_at}
                                >
                                    {slot.label}
                                </option>
                            ))}
                        </select>
                    </Deferred>
                </label>

                <label>
                    Name
                    <input
                        autoComplete="name"
                        type="text"
                        value={data.customer_name}
                        onChange={(event) =>
                            updateField('customer_name', event.target.value)
                        }
                    />
                </label>

                <label>
                    Email
                    <input
                        autoComplete="email"
                        type="email"
                        value={data.customer_email}
                        onChange={(event) =>
                            updateField('customer_email', event.target.value)
                        }
                    />
                </label>

                <label>
                    Phone
                    <input
                        autoComplete="tel"
                        type="tel"
                        value={data.customer_phone}
                        onChange={(event) =>
                            updateField('customer_phone', event.target.value)
                        }
                    />
                </label>

                <label>
                    Notes
                    <textarea
                        value={data.notes}
                        onChange={(event) =>
                            updateField('notes', event.target.value)
                        }
                    />
                </label>

                <button
                    disabled={processing}
                    type="submit"
                >
                    Request appointment
                </button>
            </form>
        </main>
    )
}
