// packages/theme-inertia-bookings-vue/resources/js/Components/Capell/Widgets/Content.vue
<script setup>
import { sanitizePublicHtml } from '../../../Support/publicHtml.js'

defineProps({
    widget: {
        type: Object,
        required: true,
    },
})
</script>

<template>
    <article class="capell-bookings-widget capell-bookings-widget-content">
        <p
            v-if="widget.data?.eyebrow"
            class="capell-bookings-widget-eyebrow"
        >
            {{ widget.data.eyebrow }}
        </p>
        <h2 v-if="widget.data?.title">{{ widget.data.title }}</h2>
        <div
            v-if="widget.data?.content"
            v-html="sanitizePublicHtml(widget.data.content)"
        />
    </article>
</template>

// packages/theme-inertia-bookings-react/resources/js/Components/Capell/Widgets/Content.jsx
import { sanitizePublicHtml } from '../../../Support/publicHtml.js'

export default function Content({ widget }) {
    return (
        <article className="capell-bookings-widget capell-bookings-widget-content">
            {widget.data?.eyebrow ? (
                <p className="capell-bookings-widget-eyebrow">
                    {widget.data.eyebrow}
                </p>
            ) : null}
            {widget.data?.title ? <h2>{widget.data.title}</h2> : null}
            {widget.data?.content ? (
                <div
                    dangerouslySetInnerHTML={{
                        __html: sanitizePublicHtml(widget.data.content),
                    }}
                />
            ) : null}
        </article>
    )
}
