// packages/inertia-vue-adapter/resources/js/Pages/Capell/Page.vue
<script setup>
import ContentWidget from '../../Components/Capell/Widgets/Content.vue'
import ImageWidget from '../../Components/Capell/Widgets/Image.vue'
import TitleWidget from '../../Components/Capell/Widgets/Title.vue'

const props = defineProps({
    page: {
        type: Object,
        required: true,
    },
})

const widgets = {
    'Capell/Widgets/Content': ContentWidget,
    'Capell/Widgets/Image': ImageWidget,
    'Capell/Widgets/Title': TitleWidget,
}
</script>

<template>
    <main class="capell-inertia-page">
        <section class="capell-inertia-page__content">
            <h1 v-if="page.title">{{ page.title }}</h1>
            <div
                v-if="typeof page.content === 'string'"
                v-html="page.content"
            />
        </section>

        <section
            v-for="container in page.layout?.containers ?? []"
            :key="container.key"
            class="capell-inertia-page__container"
            :data-container="container.key"
        >
            <component
                :is="widgets[widget.component] ?? ContentWidget"
                v-for="widget in container.widgets"
                :key="`${widget.key}:${widget.occurrence}`"
                :widget="widget"
            />
        </section>
    </main>
</template>

// packages/inertia-react-adapter/resources/js/Pages/Capell/Page.jsx
import ContentWidget from '../../Components/Capell/Widgets/Content.jsx'
import ImageWidget from '../../Components/Capell/Widgets/Image.jsx'
import TitleWidget from '../../Components/Capell/Widgets/Title.jsx'

const widgets = {
  'Capell/Widgets/Content': ContentWidget,
  'Capell/Widgets/Image': ImageWidget,
  'Capell/Widgets/Title': TitleWidget,
}

export default function Page({ page }) {
  return (
    <main className="capell-inertia-page">
      <section className="capell-inertia-page__content">
        {page.title ? <h1>{page.title}</h1> : null}
        {typeof page.content === 'string' ? <div dangerouslySetInnerHTML={{ __html: page.content }} /> : null}
      </section>

      {(page.layout?.containers ?? []).map((container) => (
        <section className="capell-inertia-page__container" data-container={container.key} key={container.key}>
          {container.widgets.map((widget) => {
            const WidgetComponent = widgets[widget.component] ?? ContentWidget

            return <WidgetComponent key={`${widget.key}:${widget.occurrence}`} widget={widget} />
          })}
        </section>
      ))}
    </main>
  )
}
